Implement session quota restrictions
celo-org/komenci pull request #102
Opened 2020-10-30 16:40 UTC by Pedro-vk

Closes #86

2020-10-31 12:03 UTC, bowd requested changes
Great work! I've added a few comments here and there.

2020-10-31 12:03 UTC, bowd commented on apps/onboarding/src/session/session.service.ts
> +      await this.update(session.id, session)
Like I said before I would remove the update from the `session.checkQuota`. And handle the update here.

2020-10-31 12:03 UTC, bowd commented on apps/onboarding/src/session/session.service.ts
> +  statusCode = 403
Let's make it a [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)

2020-11-01 12:24 UTC, bowd commented
@Pedro-vk I took this over in the weekend because it was blocking on adding another endpoint for the frontend work 🙏

2020-11-01 12:27 UTC, Pedro-vk commented on apps/onboarding/src/errors/api-error.ts
> +  _apiError: Symbol = apiErrorSymbol
I think that your second example is the most common use. Could be a string, enum or other thing inside the symbol property. But yes 👌

2020-11-01 12:28 UTC, Pedro-vk commented on apps/onboarding/src/session/session.entity.ts
> +    checkQuota(quota: SessionQuota, updateUsage: boolean = true) {
It is updated in the service, there is a good way to update a Entity from its own code?

2020-11-01 12:29 UTC, Pedro-vk commented
> @Pedro-vk I took this over in the weekend because it was blocking on adding another endpoint for the frontend work 🙏 

Sure, feel free 👌

2020-11-02 15:54 UTC, merged