Querying the identifier also returns the unblinded signature
celo-org/komenci pull request #249
Opened 2022-03-16 04:55 UTC by isabellewei

This PR is part of https://github.com/celo-org/celo-monorepo/issues/9235, and is meant to make `komencikit` compatible with the changes in https://github.com/celo-org/celo-monorepo/pull/9393. The  unblinded signature is returned in `getDistributedBlindedPepper` so that it can be passed to the attestation service for pepper verification.

2022-03-18 14:19 UTC, alecps requested changes

2022-03-18 14:19 UTC, alecps commented on packages/libs/komencikit/src/kit.ts
> +        unblindedSig: phoneNumberHashDetails.unblindedSignature
You need to add this to the response type in `./actions` too right?

2022-03-18 14:40 UTC, alecps commented
You'll also need to upgrade the version of @celo/identity used here

2022-03-21 14:10 UTC, eelanagaraj requested changes
- +1 to Alec's comment, the `GetDistributedBlindedPepperResp` needs to be updated + update ID dep as building komencikit currently fails
- komenci unit tests should pass; please update/add a test for this new returned response
- you can use the example `attestation-flow.ts` to manually test komenciki (may require redeploying the alfajores AS to a version including the ODIS changes; I had to re-update the full nodes for Espresso so it's back to the released v1.5.0): The script in its current form may not work, but you can use this hacky version: https://github.com/celo-org/komenci/blob/eelanagaraj/updated-attestation-flow/packages/libs/komencikit/examples/attestation-flow.ts

2023-01-23 12:44 UTC, closed without merging